Repository gdsc-gvp/Problem-Solving, pull requests merged in 2021-10, with the labels that each got.

#12 Create community.yml
  .github/workflows/community.yml
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#16 MODIFY PR AND ISSUE TEMPLATE
  .github/issue_template.md
  .github/pull_request_template.md
Labels: approved, Hacktoberfest, hacktoberfest-accepted

#18 ADD TWO SUM 4
  Leetcode/Readme.md
  Leetcode/Two sum IV/two_sum_4.cpp
Labels: approved, Hacktoberfest, hacktoberfest-accepted

#20 HAIL XOR
  Codechef/HAILXOR/HAILXOR.cpp
Labels: approved, Hacktoberfest, hacktoberfest-accepted

#23 chore: add a problem from a codeforces contest
  Codeforces/1560A.cpp
Labels: approved, Hacktoberfest, hacktoberfest-accepted

#31 MAXIMUM PRODUCT SUBARRAY
  Leetcode/Maximum product subarray/max_prod_subarray.cpp
Labels: approved, Hacktoberfest

#35 (DE)SERIALIZE TREE
  Leetcode/(De)Serialize tree/serialize_tree.cpp
Labels: approved, Hacktoberfest, hacktoberfest-accepted

#34 Upload B
  Codeforces/1560B/1560B.cpp
Labels: approved, Hacktoberfest

#43 Update community.yml
  .github/workflows/community.yml
Labels: approved, Hacktoberfest, hacktoberfest-accepted

#44 VALIDATE BST
  Leetcode/validate BST/validate_bst.cpp
Labels: approved, Hacktoberfest

#46 Intro to codechef
  Codechef/Readme.md
Labels: good first issue, approved, Hacktoberfest, hacktoberfest-accepted

#45 KTH LARGEST ELEMENT IN STREAM
  Leetcode/kth largest in stream/kth_largest_stream.cpp
Labels: approved, Hacktoberfest, hacktoberfest-accepted

#58 Added ADJHATE #53
  Codechef/ADJHATE.cpp
Labels: approved, Hacktoberfest

#61 112A as per issue #56
  Codeforces/112A/112A.cpp
Labels: approved

#62 118A as per issue #54
  Codeforces/118/118A.cpp
Labels: approved

#68 Capple
  Codechef/CAPPLE/capple.c
Labels: approved, Hacktoberfest

#51 upload problem 1560C
  Codeforces/1560C/1560C.cpp
Labels: approved, Hacktoberfest, hacktoberfest-accepted
